<?php


return array(
	'consumer_protection_service'   => '消费者保障服务',
	'consumer_protection_apply'   => '消费者保障申请',
	'apply_successed'   => '您的申请已成功提交',
	'apply_successed_notice'   => '我们将在三个工作日内审核您的申请，然后尽快给予答复。',
	'deposit_quota'=>'保证金额度',
	'post_deposit'=>'提交保证金',
	'frozen_cash_deposit'=>'当前需冻结的保证金金额',
	'frozen_cash_deposit_notice'=>'提交保证金前，请确保您的余额账户余额足够冻结',
	'deposit_unit'=>'元',
	'add_time'=>'申请时间',
	'c_p_list'=>'消保列表',
	'c_p_manage'=>'消保管理',
	'c_p_setting'=>'消保设置',
	'verify_c_p_list' => '待审核消保',
	'verify_type' => array(
        '1' => '审核消费者保障',
        '2' => '百分百满意',
	'3' => '七天无忧退换',
    ),
	'add_time_from' => '申请时间从',
    'add_time_to' => '至',
	'store_name' => '店铺名称',
	'owner_name' => '店主',
    'owner_name' => '店主姓名',
	'c_s_item_name' => '申请服务名称',
	'state'=>'状态',
	'not_such_consumer_service'=>'没有此项服务',

	'state_type' => array(
        '0' => '审核中',
        '1' => '申请通过',
		'2' => '拒绝申请',
    ),
	
	'c_s_type' => array(
       '1' => '审核消费者保障',
        '2' => '百分百满意',
		'3' => '七天无理由免运费上门退换',
    ),
	
	'view'=>'查看',
	'agree'=>'通过',
	'reject' => '拒绝',
	'close'=>'撤消',
	'reject_confirm'=>'您确定要拒绝该店铺的此项服务申请吗？',
	'close_confirm'=>'您确定要撤消该店铺的此项服务吗？',
	'agree_ok' => '操作成功，该项服务已开通',
    'reject_ok' => '操作成功。',
    'reject_reason' => '拒绝原因',
	'input_reason' => '请输入拒绝原因',
    'reject_title' => '您的%s申请被拒绝',
    'reject_content' => '抱歉，您的%s申请已被拒绝，原因如下： %s',
    'agree_title' => '您的%s申请已通过审核',
    'agree_content' => '恭喜，您的%s申请已通过审核。',
	'income_for_consumer_service'=>'卖家申请%s服务审核通过，进帐%s',
	'roll_back_money_for_reject'=>'您的%s申请已被拒绝，申请时冻结的金额已退回您的帐户',
	'close_ok'=>'您成功撤消该店铺的此项服务',
	'setting_successed'=>'消费者保障设置成功',
	'xfzbz_image' => '消费者保障图片',
	'xfzbz_image_note' => '建议上传消费者保障图片规格：20*20',
	'c_s_setting'   => '消费者保障设置',
	'deduct_deposit_for_agree'=>'您的%s申请已审核通过，系统扣除冻结的保障金',
	'close_error'=>'只有通过审核的服务才能撤消',
	'roll_back_money_for_close'=>'您的%s服务已被撤消，系统退还被扣除的保障金',
	'deduct_capital_for_close'=>'卖家的%s服务已被撤消，系统退还被扣除的保障金',
	'number_only' => '此项仅能为数字',
	
);
?>
